name: update-bot

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_update: ${{ steps.check_ver.outputs.is_update }}
      stable_ver: ${{ steps.check_ver.outputs.stable_ver }}
      docker_tags: ${{ steps.check_ver.outputs.docker_tags }}
    steps:
      - name: Check version
        id: check_ver
        uses: mogeko/latest-version@v1.1.2
        with:
          repo: Wind4/vlmcsd

  build:
    runs-on: ubuntu-20.04
    needs: check
    if: needs.check.outputs.is_update == 'true'
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            docker.io/${{ github.repository_owner }}/vlmcsd
            ghcr.io/${{ github.repository_owner }}/vlmcsd
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            ${{ needs.check.outputs.docker_tags }}
      - uses: actions/checkout@v3.1.0
        with:
          repository: Wind4/vlmcsd
          path: vlmcsd-source
          ref: ${{ needs.check.outputs.stable_ver }}
      - name: Build container
        run: make buildah
        env:
          IMAGE_NAME: ${{ github.repository_owner }}/vlmcsd
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ github.repository_owner }}/vlmcsd
          tags: ${{ steps.meta.outputs.tags }}
          registry: ghcr.io docker.io
