name: update-bot

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      old_ver: ${{ steps.check_ver.outputs.old_ver }}
      new_ver: ${{ steps.check_ver.outputs.new_ver }}
    steps:
      - name: Check version
        id: check_ver
        run: |
          get_ver() (curl -s "$@" | grep -Po "svn\d+" | head -1)
          OLD_VER=$(get_ver ${GHCO_URL})
          NEW_VER=$(get_ver ${REPO_URL})
          echo "::set-output name=new_ver::${OLD_VER}"
          echo "::set-output name=new_ver::${NEW_VER}"
        env:
          GHCR_URL: https://github.com/mogeko/docker-vlmcsd/pkgs/container/vlmcsd
          REPO_URL: https://github.com/Wind4/vlmcsd/releases/latest

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.old_ver != needs.check.outputs.new_ver }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: |
            ${{ github.repository_owner }}/vlmcsd
            ghcr.io/${{ github.repository_owner }}/vlmcsd
          tags: |
            type=edge
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,${{ needs.check.outputs.new_ver }}
            type=raw,latest
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ needs.check.outputs.new_ver }}
      - name: Save metadata
        run: echo ${{ toJSON(steps.build.outputs.metadata) }} > ${{ github.workspace }}/meta.json

      - name: Update metadata
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: ${{ github.workspace }}/meta.json
