name: Publish Docker Container

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: vlmcsd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME
          VERSION=`curl https://github.com/Wind4/vlmcsd/tags | grep '<a href="/Wind4/vlmcsd/releases/tag/' | cut -d '"' -f 2 | cut -d '/' -f 6 | head -1`

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      
      - name: Departure update
        run: |
          echo '{"soure_type": "Branch", "source_name": "master"}' > update.json
          curl -H 'Content-Type: application/json' --data @update.json -X POST ${{secrets.BUILD_WEBHOOK}}
