name: Publish Docker Container

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: vlmcsd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME
          VERSION=`curl https://github.com/Wind4/vlmcsd/tags | grep '<a href="/Wind4/vlmcsd/releases/tag/' | cut -d '"' -f 2 | cut -d '/' -f 6 | head -1`
          CHECK_VERSION=`curl -L https://mogeko.github.io/docker-vlmcsd/index.json | grep version | cut -d '"' -f 8`
          if [ "$VERSION" != "$CHECK_VERSION" ]; then
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag image $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          fi
          mkdir publish && cd publish
          echo "{\"date\":\"`date "+%FT%T%:z"`\",\"version\":\"$VERSION\"}" > index.json
      
      - name: Departure update
        run: |
          echo '{"soure_type": "Branch", "source_name": "master"}' > update.json
          curl -H 'Content-Type: application/json' --data @update.json -X POST ${{secrets.BUILD_WEBHOOK}}
      

      - name: Update Version Info
        uses: Mogeko/git-push@master
        with:
          GH_EMAIL: zhengjunyi@live.com
          GH_USERNAME: Mogeko
          GH_REPO: github.com/Mogeko/docker-vlmcsd
          GH_BRANCH: gh-pages
          GH_TOKEN: ${{ secrets.BUILD_TOKEN }}
          WORK_DIR: "publish"
          